timezone: America/New_York
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: my_collection
    values:
      layout: ""

collections:
  example:
    output: true
